### ISSUE TITLE
可否出一版基于webpack-dev-server的版本？

### ISSUE THREAD

**Issue by Andykeh** [colorpeach/browsersync-webpack-ssi#1]
目前使用webpack-dev-server实现HMR，没有使用webpack-hot-middleware只是参考 browsersync-webpack-ssi的默认配置项结合webpack-dev-middleware一起使用虽然也可以用，但是会出现构建两次的情况，可能是我配置的不对。
是否可以考虑下webpack-dev-server？

**Comment by colorpeach** [comment]
@Andykeh 能贴下自己的具体配置吗？ 或者可以使用 [https://github.com/uswitch/ssi-loader](https://github.com/uswitch/ssi-loader)，配置很方便，我自己也用的这个

**Comment by Andykeh** [comment]
我看了下 ssi-loader 目前只支持  block 和 include  指令，他似乎没有用 node-ssi？

**Comment by colorpeach** [comment]
@Andykeh 是的，他没用。你可以把自己的配置贴出来看下，我这边没有打包两次的问题。  
然后我看了`webpack-dev-server`的代码，他其中包括了`webpack-dev-middleware`，所以没有必要再引入`webpack-dev-middleware`，你可以把自己配置贴出来或者看看[https://github.com/webpack/webpack-dev-server/blob/master/examples/node-api-middleware/server.js](https://github.com/webpack/webpack-dev-server/blob/master/examples/node-api-middleware/server.js)这个例子，配中间件

**Comment by Andykeh** [comment]
我清楚构建两次是因为我配置了webpack-dev-server又配置webpack-dev-middleware ，
我不是特别清楚 browsersync-webpack-ssi如何配置，如果我用webpack-dev-server的话第一个参数是吧webpack-dev-server实例传进去？

**Comment by colorpeach** [comment]
[https://github.com/webpack/webpack-dev-server/blob/master/lib/Server.js#L68](https://github.com/webpack/webpack-dev-server/blob/master/lib/Server.js#L68)这里看到，可以通过`webpack-dev-server`实例的middleware属性拿到`webpack-dev-middleware`的实例。

像下面这样使用：

```
const server = new WebpackDevServer(compiler, {
	stats: {
		colors: true
	},
	setup: function(app) {
		app.use(browsersyncWebpackSsi(server.middleware, {
                    baseDir: path.join(__dirname, '../src/'),
                    encoding: 'utf-8'
                }));
	}
});
```

试试能否可行

**Comment by Andykeh** [comment]
明天尝试下，主要还是对webpack研究的不是很透彻，感谢指点

**Comment by Andykeh** [comment]
最终配置如下：
setup:function(app,_this){
        app.use(browsersyncWebpackSsi(_this.middleware, {
                baseDir: path.join(__dirname, '../src/'),
                encoding: 'utf-8'
            }))
    }

**Comment by colorpeach** [comment]
好的，那麻烦把这个issue关闭，我把`webpack-dev-server`的配置方式也加到readme里
